### ISSUE TITLE
condensing workflow

### ISSUE THREAD

**Issue by einarhjorleifsson** [fishvice/tidydatras#6]
current flow relies too much on following steps in a particular order. question if one should not hide the whole tidy and transformation process within a single function. idea to be developed in a branch.

**Comment by martinpastoors** [comment]
Have included a number of modifications; all functions renamed to "dr_" functions; in principle one function (-type) per file. Included options for downloading flexfiles. 
Adapted download all to allow for downloading of specific surveys
Included options for using locally stored files instead of webbased files
Included dr_calclengthindex for integrated solution to calculate numbers aggregated index based on length making use of all underlying functions.
